### ISSUE TITLE
about real deployment

### ISSUE THREAD

**Issue by souhaiebtar** [lobaro/ttn-private-network#2]
@Niondir really thanks for this great project, what i want to know is if i want to deploy in a server, what should i change, do i change only the hostname for the different services,

what i have now is a server with ip let say 121.54.22.12,
using my dns zone editor: i added a record from  thingsnetwork.space -> 121.54.22.12
than        discovery.thingsnetwork.space -> 121.54.22.12
router.thingsnetwork.space -> 121.54.22.12
broker.thingsnetwork.space -> 121.54.22.12
handler.thingsnetwork.space -> 121.54.22.12
networkserver.thingsnetwork.space -> 121.54.22.12

and than use those domain name as replacement for 
discovery.local.thethings.network
router.local.thethings.network
broker.local.thethings.network
handler.local.thethings.network
networkserver.local.thethings.network,

sorry for the bothering

**Comment by niondir** [comment]
If all components run on the same server you don't have to change anything. The local addresses are working just fine. 
As soon as you start to split up your services across multiple physical machines or VM's you might use docker swarm (or even Kubernetes). With docker swarm I have no experience but appreciate any input in form of documentation :)

From the outside you will be able to connect you gateway to the bridge via 121.54.22.12:1700 or you-domain.tld:1700 - this is completely independent from the docker-compose setup here.

I hope that helps.

**Comment by souhaiebtar** [comment]
thinks, i will test it,
